# Gnukhata docker compose file
# Maintainers: Sai Karthik <kskarthik@disroot.org>

version: "3.3" # optional since v1.27.0
services:
  # postgresql database
  db:
    image: postgres:12-alpine
    restart: "always"
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    volumes:
      - gkdb:/var/lib/postgresql/data

  # GNUKhata REST API Server
  gkcore:
    image: digitalfreedom/gkcore:latest
    restart: "always"
    environment:
      - GKCORE_DB_URL=postgres://gkadmin:gkadmin@db:5432/gkdata
    ports:
      - "6543:6543" #expose gkcore port to host
    depends_on:
      - db

  # GNUKhata progressive web app
  gkapp:
    image: digitalfreedom/gkapp:latest
    restart: "always"
    ports:
      - "2020:80"
    depends_on:
      - gkcore
      - ifsc-server
volumes:
  gkdb:
