# Gnukhata docker compose file
# Maintainers: Sai Karthik <kskarthik@disroot.org>
# Persistent data location is 'gkdir' folder in user's home directory
# postgres data: gkdir/postgresql
# caddy config: gkdir/caddy

version: "3.3" # optional since v1.27.0
services:
  # postgresql database
  db:
    image: postgres:12-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    volumes:
      - $HOME/gkdir/postgresql:/var/lib/postgresql/data

  # gnukhata (gkcore & gkwebapp)
  gnukhata:
    #build: docker-compose/
    image: digitalfreedom/gnukhata:devel
    restart: on-failure
    ports:
      - "6543:6543" #gkcore
      - "6544:6544" #gkwebapp
    depends_on:
      - db
      - ifsc-server
  # IFSC codes validation API server
  ifsc-server:
    image: razorpay/ifsc:latest
    restart: on-failure

  # http server
  # web:
  #   image: caddy:alpine
  #   volumes:
  #     # Caddy config file
  #     - $HOME/Caddyfile:/etc/caddy/Caddyfile
  #     # The /data directory must not be treated as a cache. Its contents are not ephemeral or merely for the sake of performance. Caddy stores
  #     # TLS certificates, private keys, OCSP staples, and other necessary information to the data directory. It should not be purged without
  #     # an understanding of the implications.
  #     - $HOME/gkdir/caddy/data:/data
  #     # config directory
  #     - $HOME/gkdir/caddy/config:/config
  #   environment:
  #     # caddy automatically adds a lets encrypt SSL certificate to a valid domain name prefixed with https://
  #     # and issues a self signed certificate if run from localhost with https://
  #     - SITE_ADDRESS=localhost
  #   ports:
  #     - "80:80"
  #     - "443:443" # for SSL
  #   depends_on:
  #     - gnukhata
