# Gnukhata docker compose file
# Maintainers: Sai Karthik <kskarthik@disroot.org>
# Persistent data location is 'gkdir' folder in user's home directory
# postgres data: ~/gkdir/postgresql

version: "3.3" # optional since v1.27.0
services:
  # postgresql database
  db:
    image: postgres:12-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    volumes:
      - $HOME/gkdir/postgresql:/var/lib/postgresql/data
      - $HOME/gkdir/logs:/gnukhata/*.log

  # IFSC codes validation API server
  ifsc-server:
    image: razorpay/ifsc:latest
    restart: on-failure

  # GNUKhata REST API Server
  gkcore:
    image: digitalfreedom/gkcore:v8.0a
    restart: on-failure
    environment:
      - GKCORE_DB_URL=postgres://gkadmin:gkadmin@db:5432/gkdata
    ports:
      - "6543:6543" #expose gkcore port to host
    depends_on:
      - db
      - ifsc-server

  # GNUKhata progressive web app
  gkapp:
    image: digitalfreedom/gkapp:v8.0a
    restart: on-failure
    ports:
      - "2020:80"
    depends_on:
      - gkcore
      - ifsc-server
    # volumes:
    #   - $HOME/gkdir/gkapp:/usr/share/nginx/
