# Gnukhata docker compose file
# This file is used on the dev server
# Maintainers: Sai Karthik <kskarthik@disroot.org>

services:
  # postgresql database
  db:
    image: postgres:12-alpine
    restart: "always"
    environment:
      - POSTGRES_USER=gkadmin
      - POSTGRES_PASSWORD=gkadmin
      - POSTGRES_DB=gkdata
    volumes:
      - gkdb:/var/lib/postgresql/data

  # REST API Server
  gkcore:
    image: digitalfreedom/gkcore:devel
    restart: "always"
    environment:
      - GKCORE_DB_URL=postgres://gkadmin:gkadmin@db:5432/gkdata
      - PYRAMID_CONFIG_FILE=${PYRAMID_CONFIG_FILE}
    ports:
      - "6543:6543" #gkcore
    depends_on:
      - db

  # gnukhata v7
  gkwebapp:
    restart: "always"
    image: digitalfreedom/gnukhata:v7.0update
    ports:
      - "6544:6544"
    volumes:
      - gkdb_old:/var/lib/postgresql

volumes:
  gkdb:
  gkdb_old:
